### ISSUE TITLE
Popups go under the assets

### ISSUE THREAD

**Issue by williambsm** [williambsm/ludum-dare-41#11]
![image.png](https://images.zenhubusercontent.com/594c578551aa2c30578292c6/98e4309e-1b35-46c8-bdb6-84a9aa941b8e)

**Comment by redman-racer** [comment]
Fixed the issue. I had to move a couple of the playlist that were having issues with some of the assets outside of the asset's container div. Everything is working now.

**Comment by williambsm** [comment]
Confirm fix
